version: '3.8'
services:

  db:
    image: "mysql:8.0.30"
    restart: 'always'
    env_file:
      - "./.env"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - db-data:/var/lib/mysql
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-u",
          "$MYSQL_USER",
          "-p$MYSQL_PASSWORD"
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis_server:
    image: redis:7.0.11-alpine3.18
    restart: always
    env_file:
      - "./.env"
    ports:
      - $REDIS_PORT:6379
    volumes:
      - redis_server-data:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass $REDIS_PASSWORD

  api:
    depends_on:
      - db
      - redis_server
    build:
      context: "./node-attendance-system-api"
    env_file:
      - "./.env"
    environment:
      - APP_PORT=$API_PORT
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
      - TEACHER_SITE_DOMAIN=$TEACHER_SITE_DOMAIN
      - STUDENT_SITE_DOMAIN=$STUDENT_SITE_DOMAIN
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - REDIS_HOST=redis_server
      - REDIS_PORT=6379
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - SMTP_HOST=$SMTP_HOST
      - SMTP_PORT=$SMTP_PORT
      - SMTP_AUTH_USER=$SMTP_AUTH_USER
      - SMTP_AUTH_PASS=$SMTP_AUTH_PASS
      - SENDER_EMAIL=$SENDER_EMAIL
    ports:
      - $API_PORT:$API_PORT
    stdin_open: true
    tty: true

  admin_site:
    depends_on:
      - api
    build:
      context: "./react-attendance-system-admin-site"
    env_file:
      - "./.env"
    environment:
      - APP_PORT=$ADMIN_SITE_PORT
    ports:
      - $ADMIN_SITE_PORT:$ADMIN_SITE_PORT
    stdin_open: true
    tty: true

  teacher_site:
    depends_on:
      - api
    build:
      context: "./react-attendance-system-teacher-site"
    env_file:
      - "./.env"
    environment:
      - APP_PORT=$TEACHER_SITE_PORT
    ports:
      - $TEACHER_SITE_PORT:$TEACHER_SITE_PORT
    stdin_open: true
    tty: true

  student_site:
    depends_on:
      - api
    build:
      context: "./react-attendance-system-student-site"
    env_file:
      - "./.env"
    environment:
      - APP_PORT=$STUDENT_SITE_PORT
    ports:
      - $STUDENT_SITE_PORT:$STUDENT_SITE_PORT
    stdin_open: true
    tty: true

volumes:
  db-data:
  redis_server-data:
